name: SkiframesGPS
options:
  bundleIdPrefix: com.skiframes
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  SWIFT_VERSION: "5.9"

targets:
  SkiframesGPS:
    type: application
    platform: iOS
    sources:
      - SkiframesGPS
    scheme:
      gatherCoverageData: false
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.skiframes.gps
      INFOPLIST_FILE: SkiframesGPS/Info.plist
      GENERATE_INFOPLIST_FILE: "NO"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      DEVELOPMENT_TEAM: ""
